### ISSUE TITLE
Modificar test de comparacion de POIs

### ISSUE THREAD

**Issue by matiaslp** [matiaslp/tp-anual-grupo1#18]

**Comment by EndlessMatt** [comment]
Que hay que hacer con este?

**Comment by matiaslp** [comment]
Ya hay un test (TestPOI_Comparacion) pero no cumple con su objectivo porque esta mal planteado.
Al integrar la entrega 3 nos encontramos con que esto no esta siendo testeado como corresponde:

Hay que hacer un test extensivo que valide que TODAS las comparaciones que se hacen en los metodos busquedaEstandar funcionan perfecto (probar nulls, comparaciones iguales y distintas).
Recomendacion, setear el parametro de distanciadeLeveinstein a cero en el test para simplificar.

**Comment by maxiquiroga93** [comment]
Primero hacer el test comparando 1 de cada tipo y ver como hacer para que no rompa, y después adaptar el método compararPOI de la clase POI, y después hacer los test por cada subclase (comparando los atributos propios de cada subclase)

**Comment by maxiquiroga93** [comment]
Ahora si, solved.

**Comment by maxiquiroga93** [comment]
le erre, este no esta resuelto, era otro

**Comment by maxiquiroga93** [comment]
Nota: No puede haber comparación entre atributos de POIs de distinto tipo porque antes de eso se compara el tipo del POI, y si es distinto sale.

**Comment by maxiquiroga93** [comment]
terminado
