### ISSUE TITLE
Modificar la estructura de paquetes

### ISSUE THREAD

**Issue by matiaslp** [matiaslp/tp-anual-grupo1#2]
En la ultima entrega Laura nos pidio:

"Seria deseable que las clases se ordenen utilizando los paquetes, en
clases que contienen logica de negocio (controllers, servicios) y clases que
contienen datos (DTOs, etc)."

**Comment by matiaslp** [comment]
Informacion provista por Laura para poder soluncionar este issue:

[http://docstore.mik.ua/orelly/java-ent/jnut/ch02_11.htm](url)

**Comment by maxiquiroga93** [comment]
hecho
