### ISSUE TITLE
Implementar la funcionalidad "Agregar Acciones"

### ISSUE THREAD

**Issue by maxiquiroga93** [matiaslp/tp-anual-grupo1#20]
Hacer el método agregar acciones, en el paquete autentificacion.funciones

Deberían poder agregarse todos los métodos a los Administradores
A los usuarios sólo se le podrá agregar Búsquedas y obtenerInformacionDePOI (las 3 están implementadas, hay que agregarlas al paquete de acciones)

Llega una lista con acciones y un usuario, y a ese usuario se le actualiza.

**Comment by matiaslp** [comment]
Completado con test incluido
