### ISSUE TITLE
Implementar BajaPOIs

### ISSUE THREAD

**Issue by maxiquiroga93** [matiaslp/tp-anual-grupo1#23]
Implementar la clase BajaPOIs, buscar por el string del JSON y fijarse si existe la fecha de baja. Si existe, dar de baja. USAR LOS METODOS DE POI_ABMC

**Comment by EndlessMatt** [comment]
Esto lo empecé a hacer en DB_POI pero no testee esa parte aún  y por lo que decís probablemente no sea la forma correcta, mírenlo si pueden y de última lo sacamos, no interfiere con nada

**Comment by matiaslp** [comment]
Lo que esta subido en DB_POI esta perfecto. La baja no se realiza en los servicios externos por lo que es necesario hacer la búsqueda local (en POI_ABMC se tiene acceso SOLO a la búsqueda "general" que abarca los servicios externos también).

Faltaría obtener los argumentos valoresBusqueda y fechaBaja desde un archivo en formato JSON.

**Comment by matiaslp** [comment]
Terminado
