### ISSUE TITLE
¿FuncEnviarEmail deberia ser una funcion que habilite o deshabilite el servicio de recibir emails para dicho usuario?

### ISSUE THREAD

**Issue by matiaslp** [matiaslp/tp-anual-grupo1#25]
Como se encuentra en este momento todas las funcionalidades son acciones que el usuario puede realizar a excepcion de esta, la cual referencia a la funcion de enviarEmail a dicho usuario. El problema es que ese metodo solo se llamaria cuando algun trigger en el sistema determina que se deben enviar emails a los usuarios que lo requieran (ejemplo: una busqueda duró mas de X segundos) por lo que el usuario no deberia tener acceso a dicho metodo.

**Comment by maxiquiroga93** [comment]
funcEnviarmail pasa a ser cambiarEstadoMail y recibe user, token y estado al que se quiere pasar.
La idea es que el usuario pueda decidir si recibir o no mails y no decidir cuando se recibe el mail (el usuario podia llamar a enviar mail cuando quiera)

**Comment by matiaslp** [comment]
esta modificacion impacta en varias partes del proyecto y dicho impacto NO FUE resuelto.

Casos:

Metodo MandarCorreoXSegundosUsuarios busca la funcionalidad "enviarMail" para saber a que usuarios enviarles email, esto deberia modificarse preguntando por el booleano en la clase Usuario.

En todo el TP se pregunta en varias partes por esa funcionalidad y deberia reemplazarse el string "enviarMail" por "cambiarEstadoMail"

**Comment by maxiquiroga93** [comment]
@matiaslp corregí lo primero, respecto a lo segundo, lo único que veo es que varias veces se usa el booleano enviarMail pero es todo en la parte de procesos, que hablamos que era otra cosa totalmente distinta: En la parte de procesos le pasas una configuración en el momento (el usuario decide si quiere enviar mail, reintentar, etc en el momento de hacer el proceso multiple), en cambio el booleano que tiene el usuario como atributo es para las búsquedas que tardan mas de X segundos. Si flashié decime, y dame una linea ejemplo donde haya que modificar así veo que onda

**Comment by maxiquiroga93** [comment]
hecho.
