### ISSUE TITLE
Al crear un usuario se deberian asignar las funcionalidades que su rol tiene por defecto

### ISSUE THREAD

**Issue by matiaslp** [matiaslp/tp-anual-grupo1#27]
Se debe modificar el constructor de Usuario.

**Comment by EndlessMatt** [comment]
Definimos las acciones por defecto en Rol.java y las asignamos por un llamado en usuario

**Comment by maxiquiroga93** [comment]
Lo hice distinto, valide directo desde el usuario, haciendo desde el enum había que hacer singleton... medio turbio singleton de un enum
