### ISSUE TITLE
TestBusquedaPorFecha

### ISSUE THREAD

**Issue by maxiquiroga93** [matiaslp/tp-anual-grupo1#33]
Falla pero creo que habían dicho que era por como manejaba cada lenguaje las fechas... chequear

**Comment by EndlessMatt** [comment]
Si te referís a este test testReporteBusquedaPorFecha si como se toma la fecha varia según el idioma del SO, igual abajo está comentada la solución para español o como lo pone el código espaï¿½ol

**Comment by matiaslp** [comment]
Se podria consultar que idioma tiene el SO y hacer el test correspondiente

**Comment by maxiquiroga93** [comment]
discutir si vale la pena.

**Comment by maxiquiroga93** [comment]
A lo' pibe' le parece que vale la pena, entonces' e'to loro' quieren que lo hagamo' cuando tengamo' tiempo

**Comment by maxiquiroga93** [comment]
Solucionado.
