### ISSUE TITLE
agregarFuncionalidad problema de encapsulamiento?

### ISSUE THREAD

**Issue by EndlessMatt** [matiaslp/tp-anual-grupo1#34]
Estaba viendo el codigo de agregarFuncionalidad y no me cierra mucho lo que hace, porque el usuario verifica si la funcionalidad existe, (No en su lista de funcionalidades sino en todas las funcionalidades) y si existe la agrega retornando true, pero si no existe retorna false.

Me parece que seria mejor que el trabajo de verificar la existencia de la funcionalidad lo haga la clase que contiene las funcionalidades y que ese booleano del usuario sea simplemente para saber si la pudo agregar o no.

**Comment by matiaslp** [comment]
Coincido que esta un poco desprolijo. Si queres modificarlo, tene en cuenta que se esta codificando varias cosas que dependen de esos métodos, por lo que no deberías cambiar su comportamiento externo y solo subir la modificación cuando sepas que anda perfecto.

Hay 2 métodos que se llaman así.
1. En la clase Usuario que es el que estas viendo, que por cierto no debería ser public porque se usa solo internamente en el package autentification.
2. En la clase AuthAPI y ese es el que deberías llamar si necesitas agregar una funcionalidad al usuario (en esta se valida también que el rol del usuario permita esa funcionalidad y que el usuario no la tenga ya asignada para evitar duplicados).

**Comment by maxiquiroga93** [comment]
hecho.
