### ISSUE TITLE
iniciarSesion

### ISSUE THREAD

**Issue by matiaslp** [matiaslp/tp-anual-grupo1#35]
El metodo iniciarSesion deberia manejar sus errores en vez de propagarlos a los objetos que los llamen. ( throws NoSuchAlgorithmException no deberia estar)

**Comment by matiaslp** [comment]
Ya le agregue el try catch pero Habria que ver en detalle como manejar el error.

**Comment by maxiquiroga93** [comment]
no hay mucho que hacer ahi, el algoritmo esta hardcodeado y no entiendo cual seria el motivo de falla, de todos modos, si falla simplemente no se inicia la sesión.
