### ISSUE TITLE
Crear 2 funcionalidades para terminales

### ISSUE THREAD

**Issue by matiaslp** [matiaslp/tp-anual-grupo1#36]
que sea posible configurar por usuario (por terminal) la activación/desactivación de notificaciones y auditoría de búsquedas.

notificaciones: Permite que si la busqueda en esa terminal duró mas de los X segundos establecidos ** _y tiene la funcionalidad de notificaciones activada_** se envian emails a todos los admin que tenga la funcionalidad de recibir emails activada.

Auditoria de busquedas: Permite que se realicen reportes de informacion correspondiente a esta terminal ** _si la misma tiene la funcionalidad de auditoria de busquedas activada_**.
Estos reportes los realizan los admin que dispongan de las funcionalidades correspondientes habilitadas.

**Comment by maxiquiroga93** [comment]
notificaciones hecho

**Comment by maxiquiroga93** [comment]
faltan los tests de ambos casos.

**Comment by maxiquiroga93** [comment]
Tocar en Reportes y testear.

**Comment by maxiquiroga93** [comment]
hecho.
