### ISSUE TITLE
BajaPOIs y otros

### ISSUE THREAD

**Issue by maxiquiroga93** [matiaslp/tp-anual-grupo1#39]
El proceso BajaPOI usa un eliminarPOi de DB_POI, pero también tenemos el paquete abmc que tiene una clase abmc con un delete que hace lo mismo... deberíamos buscar en el código cosas que tengan la misma funcionalidad.

**Comment by matiaslp** [comment]
Con los requerimientos nuevos de la entrega 4. Nos encontramos con que un "delete" en realidad no debería eliminar el POI, sino colocarle una fechadeBaja distinta de null.

Luego el proceso BajaPOI vendria a realmente eliminar los POIs a partir de su fechadeBaja en forma de batch (varios a la vez). Es decir que ambos son distintos (y al momento de hacer este comentario noto que el trabajo no esta completo por lo que se puede llevar a la confusión y creer que son duplicados cuando no lo son)

Es importante entender que esto afecta a la busqueda, que ahora tendra que buscar pois que tengan fechadeBaja igual a null e ignorar a los otros pois.

**Comment by matiaslp** [comment]
el metodo delete() de POI_ABMC ya fue modificado

**Comment by matiaslp** [comment]
Terminado
