### ISSUE TITLE
Fallos en multiples tests

### ISSUE THREAD

**Issue by matiaslp** [matiaslp/tp-anual-grupo1#40]
Gente,

Cuando realizan un cambio en algun metodo o clase que es utilizado en otras partes del proyecto para soportar funcionalidades mas complejas, es importante validar que los cambios realizados no impactan esas otras partes, es decir CORRER los TESTS.

En este momento hay failures en tests que antes andaban:
ABMC consulta
ABMC modificacion
ABMC baja
y otros

**Comment by maxiquiroga93** [comment]
Corregido testModificacionPOIInexistente

**Comment by maxiquiroga93** [comment]
a los de disponibilidad los hice para que no fallen, igualmente como depende del tiempo y el tiempo es variable, a la hora de testearlo hay que cambiar los parámetros si o si...

**Comment by maxiquiroga93** [comment]
En el test de bajas de POIs de ambc como pasó todo a ser singleton se tocan cosas y quedan modificadas, algunas las solucioné, queda 1 solo error que es porque se corre antes un test que modifica un CGP y cuando lo agarra ya tiene fecha de baja (Igualmente me parece mal que haya 1 test por cada tipo de POI porque la fecha de baja es un atributo común a todos. @BrunoBisio

**Comment by maxiquiroga93** [comment]
En Test_abmc histórico tambien pasa lo mismo, se comprueba que una lista tenga un tamaño cuando probablemente tenga otro  (De hecho arriba dice que varia por otros test(

**Comment by maxiquiroga93** [comment]
El resto de los que quedan tambien pasa lo mismo, se testea por el tamaño de una lista. No me parece un error grave los test que quedan, así que lo paso a wontfix

**Comment by maxiquiroga93** [comment]
Solucionado.
