### ISSUE TITLE
Agregar boolean a POI que indique local

### ISSUE THREAD

**Issue by matiaslp** [matiaslp/tp-anual-grupo1#42]
Es necesario que el front End sepa si un POI es local u obtenido de un servicio remoto.

Caso en los que impacta:

Al eliminar un POI solo deberiamos poder eliminar los locales ya que no hay API para eliminar remotos.

**Comment by maxiquiroga93** [comment]
Puse el atributo, y queda asignado como true, pero esto implica que cuando se traen POIs externos, ese atributo se debe asignar como false.

**Comment by EndlessMatt** [comment]
Queda para nuestro front end esta funcion
