### ISSUE TITLE
Se podria crear metodo en la clase Usuario que ejecute la funcionalidad que le pasemos como argumento

### ISSUE THREAD

**Issue by matiaslp** [matiaslp/tp-anual-grupo1#49]
De momento si un usuario desea usar una funcionalidad se realizan los siguientes pasos:

Se "chequea" si el usuario tiene dicha funcionalidad en su lista de funcionalidades
Se busca la funcionalidad en la lista de Acciones de AuthAPI
Se realiza la accion/funcionalidad

¿Todo esto podria integrarse dentro de un unico metodo?

**Comment by maxiquiroga93** [comment]
Lo habíamos hablado esto creo, de cualquier forma es lo mismo, si está del lado del usuario hay que crear un método en AuthAPI que le pida la funcionalidad, y como está ahora Usuario tiene un método que le dice a AuthAPI si ya tiene la funcionalidad, es una cuestión de responsabilidades

**Comment by matiaslp** [comment]
No es una cuestión de responsabilidades, es una cuestión de no tener las mismas 3 lineas repetidas en todos lados. Por eso la idea de integrarlo en un solo método.
Algo que reciba el string de la funcionalidad (igual que "chequearFuncionalidad") y devuelva la funcionalidad (ya obtenida desde la lista de Acciones de AuthAPI) si cumple que el usuario tiene permisos.

**Comment by maxiquiroga93** [comment]
No es lo que hace agregarFuncionalidad(fund,user) en la clase AuthAPI?

**Comment by matiaslp** [comment]
Eso agrega una funcionalidad a un usuario.

Yo estoy hablando de  si un usuario quiere utilizar una funcionalidad deberias:
Se "chequea" si el usuario tiene dicha funcionalidad en su lista de funcionalidades (chequearFuncionalidad)
Se busca la funcionalidad en la lista de Acciones de AuthAPI (getaccion)
Se realiza la accion/funcionalidad

Ej de como esta ahora:

if (admin.chequearFuncionalidad("agregarAcciones")) {
		FuncAgregarAcciones funcion = ((FuncAgregarAcciones) AuthAPI.getInstance()
						.getAccion("agregarAcciones"));
		funcion.AgregarAcciones(admin, tokenAdmin, 0, false, "");
}
--------------------------------------------------------------------------------------------------------
Ej de como quedaria:

FuncAgregarAcciones funcion = admin.obtenerFuncionalidad("agregarAcciones");
if (funcion != null) 
	funcion.AgregarAcciones(admin, tokenAdmin, 0, false, "");

**Comment by maxiquiroga93** [comment]
Ahi entendi, el unico problema que veo es que las funcionalidades no son polimorficas, entonces si hago

ejecutarFuncionalidad(String funcionalidad){
       Accion fund = this.getFuncionalidad(funcionalidad)
       if(Accion != null){
               ???????
               No hay un Accion.ejecutar() que los haga polimorfico
Puedo hacer la bestialidad de preguntar cual es el string y castear al tipo de acción.
La otra solución que se me ocurre es que al momento de ejecutar la acción se chequee (primero se valida la sesión, después se chequea la funcionalidad), me parece menos complicado.


Ejemplo

public POI obtenerInfoPOI(Usuario user, String token, Long Id){
      **String func = "obtenerInfoPOI"**
      if (validarSesion(user, token) **&& user.chequearFuncionalidad("obtenerInfoPOI")**)
                  return DB_POI.getPOIById(Id)
      else
                   return null

**Comment by matiaslp** [comment]
Se declara el metodo obtenerFuncionalidad para que devuelva un tipo Accion y cuando se llama al metodo se castea al subtipo requerido asi --->

FuncAgregarAcciones funcion =((FuncAgregarAcciones) admin.obtenerFuncionalidad("agregarAcciones"));
if (funcion != null) 
funcion.AgregarAcciones(admin, tokenAdmin, 0, false, "");

**Comment by maxiquiroga93** [comment]
Se decidió borrar chequearFuncionalidad porque hacia lo mismo que getFuncionalidad pero devolviendo un boleando
