### ISSUE TITLE
Proceso BajaPOIs BUG

### ISSUE THREAD

**Issue by matiaslp** [matiaslp/tp-anual-grupo1#52]
Si existen multiples pedidos en un mismo JSON aparentemente los resultados de un valor de busqueda son macheados con TODAS las fechas obtenidas del JSON.

Este macheo deberia ser de a pares, es decir el resultado de un valor de busqueda deberia machearse unicamente con la fecha que se encuentre consecutiva en el JSON.

**Comment by maxiquiroga93** [comment]
Hecho y testeado.
